// ==UserScript==
// @name         Wikipedia Movie Rating
// @namespace    https://en.wikipedia.org/
// @version      0.1
// @description  Display movie rating on top of the wikipedia page
// @author       Vatsal Singh
// @match        https://en.wikipedia.org/wiki/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=wikipedia.com
// @grant        GM_xmlhttpRequest
// @require      http://code.jquery.com/jquery-latest.js
// ==/UserScript==
/* global $ */

var OMDB_API_KEY = ''

var IMDB_FAVICON = 'data:image/x-icon;base64,AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEA' +
    'BAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAP0cAAAAAACPQ6AAAhqEAAoeZADvo/wAAeZkAAGFuAAC2zwAio8UA' +
    'ENHrAAAAAAAAAAAAAAAAAAAAAAAAAAAAERERERERERERERERERERERFmZmZmZmYRFoiIiIiIiGFlqqqqqqqohmUU' +
    'GBQRNBdGZRQYFBMUEEZlFBEUGBQRRmUUFxQYFBeGZRQXFBMUGYZlFBkUETQahmVaqqoqqqqGFlVVVVVVVWERZmZm' +
    'ZmZmERERERERERERERERERERERH//wAA//8AAMADAACAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AACAAQAAwAMAAP//AAD//wAA';

var ROTTEN_TOMATOES_FAVICON = 'data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQA' +
   'AAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADizDGA4sw/0OLMP/DizD/w' +
    '4sw/8OLMP/DizD/w4swwgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADizD/w4sw/8OLMP/DizD/w4sw/8OLM' +
    'P/DizD/w4sw/8OLMP/DizD/wAAAAAAAAAAAAAAAAAAAAAAAAAADizD/w4sw/8OLMP/DizD/xEvxv8aONH/GjjR/x' +
    'Evxv8OLMP/DizD/w4sw/8OLMP/AAAAAAAAAAAAAAAADizD/w4sw/8OLMP/IkHb/yJB2/8iQdv/IkHb/yJB2/8iQd' +
    'v/IkHb/yJB2/8OLMP/DizD/w4sw/8AAAAADizDQg4sw/8RL8f/IkHb/yJB2/8iQdv/IkHb/yJB2/8iQdv/IkHb/y' +
    'JB2/8iQdv/IkHb/xEvx/8OLMP/DizDPw4sw/8OLMP/IkHb/yJB2/8iQdv/IkHb/yJB2/8iQdv/IkHb/yJB2/8iQd' +
    'v/IkHb/yJB2/8iQdv/DizD/w4sw/8OLMP/IkHb/yJB2/8iQdv/IkHb/yJB2/8iQdv/IkHb/yJB2/8iQdv/IkHb/y' +
    'JB2/8iQdv/IkHb/yJB2/8OLMP/DizD/yJB2/8iQdv/IkHb/05n4v9OZ+L/Tmfi/05n4v9AWuD/IkHb/yJB2/8iQd' +
    'v/IkHb/yJB2/8iQdv/DizD/w4sw/8iQdv/I0Lb/05n4v9OZ+L/Tmfi/05n4v9OZ+L/Tmfi/z9b4P8iQdv/IkHb/y' +
    'JB2/8iQdv/IkHb/w4sw/8OLMP/IkHb/05n4v8xTd7/IkHb/yJB2/9NZ+L/Tmfi/05n4v8iQdv/IkHb/yJB2/8iQd' +
    'v/IkHb/yJB2/8OLMP/DizDBCJB2/8wTd7/IkHb/y+pb/8PLsL/IkHb/yJB2/8iQdv/IkHb/yFA2v8gP9n/IkHb/y' +
    'JB2/8hQNr/DizDFgAAAAAOLMP/N1Pe/0dh4f8iQdv/L6hw/yeMg/8OLMP/DizD/yWDif8vqHD/IG+W/yJB2/8iQd' +
    'v/DizD/AAAAAAAAAAAAAAAAA4sw/8iQdv/IUDa/w8vwf9LvYj/L6lw/zGpcv9KvIf/ID7Y/yJB2/8iQdv/DizD/w' +
    'AAAAAAAAAAAAAAAAAAAAAjl2H/I5dh/yieZ/8jl2H/S72I/y+ocP9LvYj/KaBp/yuiav8jl2H/I5dh/wAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJptk1COXYf0jmGL5I5dh4C6mbv8jl2ECAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALqZu/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AA+B8AAOAHAADAAwAAgAEAAIABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIABAACAAQAAwAMAAMAHAAD4PwAA/v8AAA==';

var METACRITIC_FAVICON = 'data:image/x-icon;base64,AAABAAIAEBAAAAAAAABoBQAAJgAAACAgAAAAAAAAqA' +
    'gAAI4FAAAoAAAAEAAAACAAAAABAAgAAAAAAEABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAN4P8AdHR5ALq6vQ' +
    'AtQEYANp3AADBwhgDd3d8AKR8XAJSUmAA2wOcAVVZZAEKJngAxWWgArqalAC3a/wA+MzAAy8vOACIQAgBlZWkAL7' +
    'DUAEh3jQAqLCsAh4iMAD5jdAAWFhEAFAEAAEGXsgBAqs8APlRcAEaivgBtXlwAPDw+AEdtgAAtNjkATExQAB3c/w' +
    'B9fYEA1NXXAC9newAPDwcA5eXnAMPDxgCUi4wAp6qvAB0dGgAuJiEAPGp+ACpdcAAhFw8ARICYAESOpwAkJiQAOU' +
    'JGADmEngAxMTEANzc3AGprbwAXCgAAOS8qAGBgZAAj4v8AG+T/AA0KAQBBcoEAFxMKAEE4NQAxLCkALNP/AEVziA' +
    'A0xOwAGBoWAK2qrAAfEwcALSIcACje/wA2XWgAF97/AEaTqgAnGA8ANLzjANHR1AC2t7oAICAeAB8bFQAzW20AEg' +
    'YAAA8AAAApKScAQW99AC4uLQBGe4sA1tjaAM7O0AAvKSYAIxMFABHf/wC8vMAAMi8tADQ1NQA5OToAQoWdAGJjZg' +
    'Ah3P8ALCckABkHAAAlGhEApaitABrc/wAAAAMAKyEaADMzMwBDcYMAKtX/ANLT1QAoHRgAGuL/AB/b/wAWAgAAKh' +
    '8ZABjc/wACAAAAEQAAACYmJAAeHhsAJSUjADArKAAxLiwALy8uADAwMAAQ4P8AHN3/AB7d/wAg2v8AMCwqAC0uLg' +
    'AxMjIARI2mAE1NUABgYWUAG9z/AB3b/wAt0/8AIhADAB4eGgApHhcALSckAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAHYljSUAAAAAAAAAAAAAeRA3MBZmR2EAAAAAAAAAYU8XdGtKS4BaTo8AAAAAAl' +
    'x3VytdOFtfkB5OAAAAjh9qQi0BAWUagjkTcYMAAEwjWGwBCIEpDHCIf4cLAAAGk0kBXnB6ZwFifomSMyVoB0MBAQ' +
    'xuPQEBJn19ayKNjooygRIEAwEBOnohGAkZbQAdREAkAQEBFHpZUgEgMYQAhjZvNYsKAXwucwEPaRUAAG0cUGNIkQ' +
    'EnKgFTew4/AAAAg0FgL1SMAQEsGwU+AAAAAACDDWR4OzwRVU0+RQAAAAAAAE5yNEZWKFF1AAAAAAAAAAAAAI5thY' +
    'UAAAAAAAD8PwAA8A8AAOADAADAAwAAgAEAAIABAACAAAAAAAAAAAAAAACAAAAAgAEAAIABAADAAwAA4AMAAPAPAA' +
    'D8PwAAKAAAACAAAABAAAAAAQAIAAAAAACABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AQ46qABvc/wBGRkgAuL' +
    'i7AIqLjwArIxwAQmh6AECx3ADb3N0Ab29zADfH9gA0VGIAWFlcABsRBQA0NDUA7e7vAMnJzABFfJMAQZ/BAH19gQ' +
    'CsrLAAM0BGABoaFgAs1P8AQlxsAGJjZwA9TFUAOb3lAE9QUgCUlJgAKysqANLT1QBEcYUA9/f3AESVuAAODQYAQK' +
    'fMAL/AwwA9PT4ARYOeACgcEwB2dnoAQFdiACAgHgA2LysAO0ZMADTO/wA9NDAAhYWJAGhpbAAgGA8AFAkAACYmJA' +
    'A4we0AJNj/AEpLTQA8t+AALicjAEOUsAA+UVwAIh0XAM3O0ACwsbQALy8vADk5OQBBQUMAXl9iAEebvwBEh6QAQW' +
    'yBAOrq6wDW1tkAMc36ADErKAA5QEUAKh8XABwUCgD7+voAGBcSAB0dGgA0x/EARX+YAHJzdwBEeI8AGQ4BAD1KUA' +
    'D09PQARpGzAFVWWQA4PUAAQVloAEFgbwAw0f8AKigmACMjIABSUlUAf4CEAEKhxQA6QkgAINr/ACjW/wAkGxMAMz' +
    'AuAEOZuQDd3uAA0NDTAB4aFQA5xPQAMS0sADIyMgCNjZEAh4eMADXE7wA1wusAKiUfAD5AQQBHSEoAQpa1AExMUA' +
    'A+t+MANjc5AEWLqgBDjKcA2NjbAC0tLABgYWQAZGVpAG1tcQAtJiAAHBUNADfM/wAoHRUA7OztANTV1wDLy80AHB' +
    'wYACshGgA2NjYAOjo7AESbvwCJiY0APk5XAEWGogB0dXgAcHF1AENmeAAyz/8AQK/aANna3AAdEwgAHx8cACIiHw' +
    'AsJB4AKiopAC8qJwAwLCkAMTEwADUzMwBCQ0QAOkRKADxITwBNTlEAUFFUAFZXWwBBXmsAQ2l8APX29wAd2/8AIt' +
    'n/ACbX/wAq1f8ALdP/ADnF9gAxLy0ANzc4ADY5OgA5QUYAO0dNAD1LVABBW2kARG+EACgoJgDIyMsAGhAEABsZFQ' +
    'AhHBYAHh4bACkeFgAkJCEALSciAC4nIQAnJyUAMCsoACwsKwAuLi4AMzMzADo/QwBGR0kAPElRAHx8gABpam0AX2' +
    'BjANzc3gAf2/8AL9L/ADPO/wA1zP8AHBEGADbH9wA4xfQAuLm8ABsbFwAdGxcAJBwUACgdEwAgIBwAKiAZACEgHQ' +
    'AhIR4ALCMdAC0lHgAtJB8ALCUfACYlIwArKikAMC0qADIvLgAwMDAAMjAwADQ0MwA1NTYANDU2ADU2NwA4ODgAOT' +
    'k6AEJCQwA6Q0kARUZIAHZ3ewBFfpcAdHR5ADxMUwBhYWUAQmBuAPf3+AD09PUA29vdANjY2gAd3P8AItr/ACLY/w' +
    'Am2P8AKtb/ACrU/wAAAAAAAAAAAAAAAAAAADAwMDAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDAwlF7OXs8wMD' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAw0NCtZaoZMNJeZmWrlIQwAAAAAAAAAAAAAAAAAAAAMIQZ+jeQ9Y+hssgsIhRm+8' +
    '+EMAAAAAAAAAAAAAAAAITPqXIIscCXNEucvweKwvN3ZRmEMAAAAAAAAAAAAACElPo8er1LmTl2mYsQEBDmioKmGf' +
    '2EMAAAAAAAAAAA0JT6E5qCsJiMqIaLLYsQEBDp5CqhUv2EMAAAAAAAADAwAym9nbCYQmoBAZYEmxAQEBAQEIWhGR' +
    'mEAAAAAAAwhKomO5x6mOvMAQEBARUtxRAQEBAQECoaZZQwAAAAADBerC+KsNmw+AEBAQFxNp5vQRAQEBAQ5ookZY' +
    'QwAAAAhM17iugti/kBAQEBjlF+6CBBm4sQEBDpB7P/lDAAADCUZhzeLehJAQEBAQa8w+jVgNTsmYsQEBBvO438MA' +
    'AAMKwJn2zohwEBAQFwvMPo1WEBAbjomxAQEBDak2UwAAAwZUbXBH0BAQEBH7zD6NWkAQEBAZabQRAQEIK0rZQwAD' +
    'D7Rw8nAQEBAWubt+jVHgEBAQEBCyCeEBAQwluuzjAAMDinZyg/AQEBBYnBUKMBAQEBAfQYxcVgIItu6nkZMAAwOK' +
    'eC26AVYgH3fzZ/AQEBAQEbGMVB4cpDvmjqeRkwADD7tgeLwyVaAQEBCgEBAQEBgBhv5dUrAbh+u8ZtrTAAMGWQ4B' +
    'Dnm+j3AQEBAQEBATMYb+XVkQEBASEuF62UMAAwrJWerxAQLUQBAQEBAQHJUG+e1VQBAQEBATENZTAAADCUrLTdEB' +
    'Bv3MsS90gBARC+xBiSAQEBAVjtTkX8MAAAANCpkNoQEBBvmcVCeAEBfyUt8gEBAQGo7zUvGZQwAAAAMF4ZZAeLEB' +
    'AQxInrAQEjMhYBAQEB9u+6ilmphDAAAAAwhPtjmsIQEBAQQeKIAQEBAQEBAU/HUdhcqpQwAAAAAAAwMPpTTePpEB' +
    'AQ3A4BAQEBAQERdlFNskr+hAAAAAAAAADQlPpV2r8QEBDFLYEBAQEBQHXWhUxzOIQwAAAAAAAAADCEXql8xYXCEO' +
    'ie3ATwYqVf0d8sSjiEMAAAAAAAAAAAADCElPodXRAHijucPoO5VnRXAvushDAAAAAAAAAAAAAAAAAwhKypOvG1or' +
    'JM7j2naaxllIQwAAAAAAAAAAAAAAAAAAAw0DAZZTheDNMwrGU4lIQwAAAAAAAAAAAAAAAAAAAAAAAAMDAwz17Ozl' +
    '6UMDAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDAwMDAAAAAAAAAAAAAAAAAA//wf///AA///AAD//gAAP/wAAB' +
    '/4AAAP8AAAB+AAAAfAAAADwAAAAcAAAAGAAAABgAAAAYAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAAGAAAABwA' +
    'AAAcAAAAHAAAAD4AAAB/AAAAfwAAAP+AAAH/4AAD//AAD//8AD///8H/8=';

var RATING_TO_FAVICON = {
    'Internet Movie Database': IMDB_FAVICON,
    'Rotten Tomatoes': ROTTEN_TOMATOES_FAVICON,
    'Metacritic': METACRITIC_FAVICON
};

(function() {
    'use strict';

    var imdb_links = [];
    var links = document.getElementsByTagName("a");
    for(var i=0, max=links.length; i<max; i++) {
        if (links[i].href.indexOf("https://www.imdb.com/title/") !== -1){
            imdb_links.push(links[i].href);
        }
    }

    if (imdb_links.length == 0) {
        console.warn("No IMDB URL found on the page")
        return
    }

   var url_obj = new URL(imdb_links[0])
   if (url_obj.pathname.split(/\//).length < 3) {
       console.warn("IMDB URL doesn't contain a title ID")
       return
   }

   if (OMDB_API_KEY.length == 0) {
      console.warn("OMDB_API_KEY is not defined")
      return
   }

   var title_id = url_obj.pathname.split(/\//)[2]
   var res = GM_xmlhttpRequest({
           method: "Get",
        url: `http://www.omdbapi.com/?i=${title_id}&apikey=${OMDB_API_KEY}`,
        onload: function (response) {
            var movie_info = JSON.parse(response.responseText)
            console.log (movie_info);
            var wiki_title = $('#firstHeading');
            var ratingContainer = $('<div id="ratingContainer"></div>');
            createRatings(ratingContainer, movie_info.Ratings);
            ratingContainer.insertBefore(wiki_title);
            ratingContainer.css({"float": "right", "padding": "10px 0 10px 0", "display": "flex"});
        }
       })
   }
)();

function createRatings(ratingContainer, ratings) {
    for (var key in ratings) {
        if (ratings[key].Source in RATING_TO_FAVICON) {
            $("<img />")
                .attr("src", (RATING_TO_FAVICON[ratings[key].Source]))
                .attr("alt", "IMBD")
                .attr("width", "20")
                .attr("height", "20")
                .appendTo(ratingContainer);
            $("<p />")
                .text(ratings[key].Value)
                .attr("display", "inline")
                .attr("style", "padding: 0px 10px 0px 10px")
                .appendTo(ratingContainer);
        }
    }

}
